#!/bin/bash
# configure the server with new parameters

apt-get update -y && apt-get upgrade -y
apt-get install nginx -y
chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
line="\\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "48i $line" /etc/nginx/sites-available/default

mkdir -p /var/www/default
echo "Ceci n'est pas une page" > /var/www/default/404.html
line1="\\\tlocation = /404.html {\n\t\t root /var/www/default;\n\t}"
sed -i "29i $line1" /etc/nginx/sites-available/default
line2="\\\terror_page 404 /404.html;"
sed -i "32i $line2" /etc/nginx/sites-available/default

q='"'
host=$(hostname)
line3="\\\tadd_header X-Served-By $q$host$q;"
sed -i "58i $line3" /etc/nginx/sites-available/default

service nginx restart
