#!/usr/bin/env bash
# install and configures HAproxy on lb-01 server
# sends traffic to web-01 and web-02 using roundrobin algorithm

apt update -y
apt upgrade -y
apt install haproxy -y
line="\nfrontend web_frontend\n\tbind*:80\n\tdefault_backend web_backend\nbackend web_backend\n\tbalance roundrobin\n\tserver web01 3.84.255.71:80 check\n\tserver web02 54.236.48.24:80 check"

sed -i "$ a $line" /etc/haproxy/haproxy.cfg
service haproxy restart
