#!/usr/bin/env bash
# install and configures HAproxy on lb-01 server
# sends traffic to web-01 and web-02 using roundrobin algorithm

apt update -y
apt upgrade -y
apt install haproxy -y
line="frontend web_frontend\n bind*:80\n default_backend web_backend\nbackend web_backend\n server web01 3.84.255.71:80 check\n server web02 54.236.48.24:80"

sed -i "$ a $line" /etc/haproxy/haproxy.cfg
service haproxy restart
