#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# 15 - SIGTERM
# 3 - SIGQUIT
# 2 - SIGINT (ctrl-z)
# Either the string or the integer can be used to refer to the signal

trap "echo I hate the kill command && sudo rm /var/run/myscript.pid; exit" 15
trap "sudo rm /var/run/myscript.pid; exit" 3
trap "echo Y U no love me?!" 2

echo $$ > /var/run/myscript.pid

i=0
until [ "$i" -eq 1 ]
do
	echo "To infinity and beyond"
	sleep 2
done
