#!/usr/bin/env bash
# This script runs nginx as non-root user nginx

service nginx stop
pkill nginx
pkill apache2
sed -i -E 's/#user.+\;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chown -R nginx:nginx /etc/nginx/ /var/run/ /var/log/nginx
chmod +rw /etc/nginx/nginx.conf
su -l nginx -c 'service nginx start'
